### PR TITLE
Graphql set up

### PR DESCRIPTION
**Pull request by ClayAsh**
## What this PR Covers  
  This PR adds Graphql, creates mutation and type files, and includes a test for create user.
  
## Type of Content in PR  

- [X] Spec Files
- [ ] Controllers / Facades / Poros
- [ ] Service Requests
- [X] Route Change
- [X] Gemfile Update
- [ ] Other:  

Is this a fully completed API Endpoint?  

- [ ] yes - API Endpoint: 
- [X] no  

## Simplecov 100% Coverage  
- [ ] yes
- [X] no  
If no, what files are not being covered?  
There are a couple Graphql methods that aren't fully tested yet.
## Tested on Localhost/Postman  
- [ ] yes
- [X] no  
If no, why was it not?  

## Additional Comments

### CODE REVIEW

**Comment by enalihai** [comment]
This looks great. I think I understand what its doing, I was looking a lot at mutations in my research. 

One thing is, I would add `/.DS_Store` to the .gitignore file and remove the DS_Store from this PR before it gets merged. It takes a snapshot of your own personal files that can mess with other contributors when they pull it down. I am going to select that I have reviewed this PR, and once the ds_store is removed / added to .gitignore, i believe it should be good to go. 

great work!

**Review by enalihai — CHANGES_REQUESTED** [review]
Read above comment before merging.

**Review by enalihai — CHANGES_REQUESTED** [review]
here is the change to .gitignore

**Review by enalihai — APPROVED** [review]

**Review by enalihai — APPROVED** [review]
this actually didnt have anything changed in it.

**Comment by deannahburke** [comment]
Merging, not sure about DS store file but going to take a look with Clay after PR is merged and make sure it's ignored.

**Pull request merged**
